import{test}from "@playwright/test"
//test("mouse",async({page})=>{
    //......vertical...........
//  await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabVertical")
//  await page.waitForTimeout(2000) 
//  await page.mouse.wheel(0,1000) 
//  await page.waitForTimeout(2000)
//  await page.mouse.wheel(0,-1000) 
//  await page.waitForTimeout(2000)
 //.......horizontal.............
//  await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabHorizontal")
//  await page.waitForTimeout(2000) 
//  await page.mouse.wheel(1000,0) 
//  await page.waitForTimeout(2000)
//  await page.mouse.wheel(-1000,0) 
//  await page.waitForTimeout(2000)
 //.......scroll to perticular elemrnt by using method called scrollIntoViewIfNeeded()
//  await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabVertical")
//  await page.waitForTimeout(2000)
//  await page.locator('//input[@type="checkbox"]').scrollIntoViewIfNeeded()
//  await page.waitForTimeout(2000)
// })
test("drag and drop",async({page})=>{
    //.......moving/drag and drop mouse actions.........
    // await page.goto("https://demoapps.qspiders.com/ui/dragDrop?sublist=0")
    // await page.locator('//div[text()="Drag Me"]').hover()
    //  await page.waitForTimeout(2000)
    // await page.mouse.down()
    //  await page.waitForTimeout(2000)
    // await page.mouse.move(200,500)
    //  await page.waitForTimeout(2000)
    // await page.mouse.up()
    //  await page.waitForTimeout(2000)
    //  //............drag and drop to targeted element............
    //  await page.goto("https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2")
    //  await page.locator('//div[text()="Mobile Charger"]').hover()
    //  await page.waitForTimeout(2000)
    //  await page.mouse.down()
    //  await page.locator('//div[text()="Mobile Accessories"]/..').hover()
    //  await page.waitForTimeout(2000)
    //  await page.mouse.up()
    //  //.............d&d by taking element location................
    //  await page.goto("https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2")
    //  await page.locator('//div[text()="Mobile Charger"]').hover()
    //  await page.waitForTimeout(2000)
    //  await page.mouse.down()
    //  let box=await page.locator('//div[text()="Mobile Accessories"]/..').boundingBox()
    //  await page.mouse.move(box.x,box.y)
    //  await page.waitForTimeout(2000)
    //  await page.mouse.up()
     //...............dragto() method................................
     await page.goto("https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2")
    let source= page.locator('//div[text()="Mobile Charger"]')
    let target= page.locator('//div[text()="Mobile Accessories"]/..')
    await page.waitForTimeout(2000)
    await source.dragTo(target)
    await page.waitForTimeout(2000)

})